In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
t=np.linspace(-5,5,5001)
t0=t[0]
dt=t[1]-t[0]
print(len(t))
x=np.array([1,2,3])
pos=x 
y=np.full_like(x,np.nan,dtype=float)
# no idead on how to convert x into an array filled with NAN
left=np.floor(pos).astype(int)
right=np.ceil(pos).astype(int)
# left and right are int arrays, M = len(x). 
# Write the boolean mask that's True only where the index pair is in range.
M=len(x)
valid=(left>=0) & (right<M)

n = np.arange(-25, 26)
Omega0,phi=1.0,1.0
x=3*np.cos(Omega0*n+phi)
# x2=3*np.cos(Omega0*(n-n0)+phi)





#  Mask syntax
x = np.array([1, 5, 2, 8, 3])
mask = (x >= 2) & (x <= 5)
print(x[mask])

5001
[5 2 3]


In [4]:
ar1=np.array([1,2,3,4,5])
ar2=ar1.copy()
ar3=ar1.view()

ar2[0]=500
print(ar1, ar2)
ar3[0]=600
print(ar1,ar2,ar3)

# view te change korle original tao change hoy, copy te change hoy na. 


[1 2 3 4 5] [500   2   3   4   5]
[600   2   3   4   5] [500   2   3   4   5] [600   2   3   4   5]


In [5]:
y[valid]=0.5*(left[valid]+right[valid])
t_query=t/k
def time_reverse(x):
    return x[::-1]

xe=0.5*(x+time_reverse(x))
xo=0.5*(x-time_reverse(x))

NameError: name 'k' is not defined